<a href="https://colab.research.google.com/github/Amrithraj7/LEARN.-PI/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [20]:
import numpy as np
vector_a = np.array([[12,7,3],
                     [4 ,5,6],
                     [7 ,8,9]]) 
vector_b = np.array([[5,8,1,],
                     [6,7,3,],
                     [4,5,9]])
print('a=',vector_a)
print('b=',vector_b)
product =np.dot(vector_a, vector_b) 
 
print("Dot Product  : \n", product)

a= [[12  7  3]
 [ 4  5  6]
 [ 7  8  9]]
b= [[5 8 1]
 [6 7 3]
 [4 5 9]]
Dot Product  : 
 [[114 160  60]
 [ 74  97  73]
 [119 157 112]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [19]:
 
 
 
import numpy as np 
 
n_array = np.array([[55, 25,15], [30, 44,2],[11,45,77]]) 
 
print("Numpy Matrix is:") 
 
print(n_array) 
 
det = np.linalg.det(n_array) 
 
print("\nDeterminant of given 3X3 matrix:") 
 
print(int(det))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Determinant of given 3X3 matrix:
137180
