<a href="https://colab.research.google.com/github/Amrithraj7/LEARN.-PI/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [101]:
import numpy as np
random_matrix_array = np.random.rand(3, 4)
print(random_matrix_array)

[[0.39969664 0.9471183  0.02424048 0.9670621 ]
 [0.17973366 0.65407752 0.06439872 0.53236926]
 [0.88319363 0.51672587 0.979614   0.07132411]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [99]:
import numpy as np
arr1=array([[5,6,7,7],
        [3,6,7,9],
        [6,7,4,2],
        [4,6,7,9]])
 
arr2=array([[5,7,9,0],
        [7,9,4,1],
        [5,8,9,0],
        [6,8,0,0]])
arr3=arr1.reshape(2,8)
arr4=arr2.reshape(2,8)
a=np.hstack((arr3,arr4))
b=np.vstack((arr3,arr4))
print(a)
print(b)

[[5 6 7 7 3 6 7 9 5 7 9 0 7 9 4 1]
 [6 7 4 2 4 6 7 9 5 8 9 0 6 8 0 0]]
[[5 6 7 7 3 6 7 9]
 [6 7 4 2 4 6 7 9]
 [5 7 9 0 7 9 4 1]
 [5 8 9 0 6 8 0 0]]
